# Generated by Django 6.0.2 on 2026-04-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WordCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='game.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='WordSum',
            fields=[
                ('wordcombination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.wordcombination')),
                ('addend1', models.CharField(max_length=100)),
                ('addend2', models.CharField(max_length=100)),
                ('sum_word', models.CharField(max_length=100)),
            ],
            bases=('game.wordcombination',),
        ),
    ]
