# Generated by Django 6.0.2 on 2026-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addend1', models.CharField(max_length=100)),
                ('addend2', models.CharField(max_length=100)),
                ('sum_word', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('addend1', 'addend2', 'sum_word')},
            },
        ),
    ]
