# Generated by Django 6.0.2 on 2026-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_duel_duelprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='for_duel',
            field=models.BooleanField(default=False),
        ),
    ]
