# Generated by Django 6.0.4 on 2026-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_nullify_existing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
    ]
